services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    volumes:
      - ./packages/backend:/app
      - ./packages/backend/node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - PORT=3000

  frontend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '5173:5173'
    volumes:
      - ./packages/frontend:/app
      - ./packages/frontend/node_modules:/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
